services:
    pgadmin:
        container_name: pgadmin4_container
        image: dpage/pgadmin4
        restart: always
        environment:
          PGADMIN_DEFAULT_EMAIL: admin@admin.com
          PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - "5050:80"
        depends_on:
            - postgres
        networks:
            - backend

    postgres:
        container_name: postgres_container
        image: postgres:15
        environment:
            POSTGRES_DB: gym-db
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
        volumes:
            - ./pg_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - backend
volumes:
  pg_data:

networks:
  backend:
    driver: bridge
